### ISSUE TITLE
odoo_smtp can't reach external SMTP servers

### ISSUE THREAD

**Issue by nqb** [lefilament/ansible_role_odoo_docker#10]
Hello,

I suppose `odoo_smtp` is a SMTP relay used by `odoo` container to send emails.

If variable `mailname` is defined in inventory, `docker-compose.yml` file for prod instance contain a `smtp` container attached to one network `email_proxy`. But this network is an internal network and doesn't allow `smtp` container to reach external SMTP servers.

I suppose `smtp` container should be attached to two networks:
- email_proxy
- email_public

**Comment by remi-filament** [comment]
My bad, the endif was not in the correct position (I had an extra if in order to be able to allow to define networks as internal or external).
Fixed with 5645ea50f771a2798d66f94b92e753fa4e26e7d5

Indeed, the idea is to block non authorized external communication (with whitelists, therefore you need email container which is able to discuss on Internet).
You can have a look here: 
![Docker Odoo LF](https://user-images.githubusercontent.com/30716308/111771158-a1c8ab00-88ab-11eb-86c5-ada879851929.jpg)


Thank you for reporting !

**Comment by nqb** [comment]
Thanks for the fix and the diagram (really helpful !)
