### ISSUE TITLE
Undefined variable lf_gitlab_ro_privkey

### ISSUE THREAD

**Issue by ni-ka** [lefilament/ansible_role_odoo_docker#11]
Hi,

I am trying to setup a odoo host using this role, but am getting the following error:

```
TASK [ansible_role_odoo_docker : PROD copy private GitLab ssh keys file] ***********************************************
fatal: [odoo.kaikai.dev]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'lf_gitlab_ro_privkey' is undefined\n\nThe error appears to be in '/home/nils/.ansible/roles/ansible_role_odoo_docker/tasks/main.yml': line 350, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: PROD copy private GitLab ssh keys file\n  ^ here\n"}
```
It looks like a variable lf_gitlab_ro_privkey needs to be defined, but I can't find any explanation in the documentation. Are private ssh keys needed by default?

Cheers!

**Comment by remi-filament** [comment]
Hi @ni-ka, you are right, I have overseen this variable.
This one is used to retrieve private git repos in Docker Odoo image, but it is not mandatory, so I just fixed it by adding a default('') so that if not defined it should create an empty file and not FAIL on that one.

Also I have renamed that variable to git_modules_privkey and added description in README.

Everything should be fixed with this commit : https://github.com/lefilament/ansible_role_odoo_docker/commit/36e58f3ebb988cfeeffd28220cc1ff58d122fb3a

Thank you for pointing this issue !
Best Regards,

**Comment by ni-ka** [comment]
Thanks! I think there was a couple of other minor things when using, for example I needed to add a (empty) inventory group [maintenance_contract] to avoid an error. Currently struggling with[ansible_role_docker_server and will create an issue there shortly.
